project 'JGNavBarDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JGNavBarDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGNavBarDemo

   pod 'SDWebImage', '~> 3.7.6'

    #UI
    pod 'SDCycleScrollView','~> 1.64'

  target 'JGNavBarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGNavBarDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
